# Generated by Django 2.1.7 on 2019-03-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The code that users will enter for the discount.', max_length=20)),
                ('percent', models.FloatField(default='5', help_text='Percent off that will be applied from this coupon.')),
            ],
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the item.', max_length=100)),
                ('description', models.CharField(help_text='The description of the item.', max_length=100)),
                ('price', models.FloatField(default='5.00', help_text='The price of the item.')),
                ('visible', models.BooleanField(default=True, help_text='Display this item publicly?')),
            ],
            options={
                'db_table': 'store_item',
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='eligible_items',
            field=models.ManyToManyField(help_text='What items can this coupon be used on?', to='store.StoreItem'),
        ),
    ]
