# Generated by Django 2.2.1 on 2019-05-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the product that you are going to sell.', max_length=100)),
                ('description', models.TextField(help_text='A description of the product.')),
                ('price', models.FloatField(default='4.99', help_text='The price of the product.')),
                ('is_stocked', models.BooleanField(default=True, help_text='Is the product in stock?')),
            ],
        ),
    ]
