# Generated by Django 2.1.7 on 2019-03-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20190326_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeitem',
            old_name='visible',
            new_name='is_visible',
        ),
        migrations.AddField(
            model_name='storeitem',
            name='is_stocked',
            field=models.BooleanField(default=True, help_text='Is this item in stock?'),
            preserve_default=False,
        ),
    ]
