# Generated by Django 2.1.7 on 2019-03-26 22:09

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20190326_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='image',
            field=models.ImageField(default=0, help_text='The image that will be displayed for the item on the store page.', upload_to=store.models.store_upload_path),
            preserve_default=False,
        ),
    ]
