# Generated by Django 2.1.7 on 2019-03-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_storeitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='is_free_shipping',
            field=models.BooleanField(default=True, help_text='Does this item have free shipping?'),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='is_stocked',
            field=models.BooleanField(default=True, help_text='Is this item in stock?'),
        ),
    ]
