# Generated by Django 2.1.7 on 2019-03-26 22:17

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20190326_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='image',
            field=models.ImageField(help_text='The image that will be displayed for the item on the store page.', upload_to=store.models.store_upload_path, verbose_name='Store Image'),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='is_free_shipping',
            field=models.BooleanField(default=True, help_text='Does this item have free shipping?', verbose_name='Free Shipping?'),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='is_stocked',
            field=models.BooleanField(default=True, help_text='Is this item in stock?', verbose_name='Stocked?'),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Display this item publicly?', verbose_name='Visible?'),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
