# Generated by Django 2.1.7 on 2019-03-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20190326_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='rating',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
