# Generated by Django 2.1.7 on 2019-03-26 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0009_auto_20190326_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'store_cart',
            },
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='description',
            field=models.CharField(help_text='The description of the item.', max_length=150),
        ),
        migrations.AddField(
            model_name='usercart',
            name='items',
            field=models.ManyToManyField(help_text='The items that are in this users cart.', to='store.StoreItem'),
        ),
        migrations.AddField(
            model_name='usercart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
