# Generated by Django 2.1.7 on 2019-03-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20190326_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
