# Generated by Django 2.1.7 on 2019-03-26 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_usercart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrating',
            name='author',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='item',
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='author',
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='item',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='rating',
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
