# Generated by Django 2.2.1 on 2019-05-13 02:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
