# Generated by Django 2.2 on 2019-05-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='icon',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
