# Generated by Django 2.2 on 2019-05-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forum_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='icon',
            field=models.CharField(default='fas fa-comments', max_length=20),
        ),
    ]
