# Generated by Django 2.2.1 on 2019-05-13 02:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20190512_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
