# Generated by Django 2.2.1 on 2019-06-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190512_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Locked', 'Locked'), ('Pinned', 'Pinned')], default='Open', max_length=20),
        ),
    ]
