# Generated by Django 2.2.1 on 2019-06-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_topic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('1', 'Open'), ('2', 'Locked'), ('3', 'Pinned')], default='Open', max_length=20),
        ),
    ]
