# Generated by Django 2.2.1 on 2019-05-31 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_reaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='result',
            new_name='react',
        ),
    ]
