# Generated by Django 2.1.7 on 2019-03-28 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, help_text='The category that the post will be listed under.', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
    ]
