# Generated by Django 2.1.7 on 2019-03-28 20:54

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190328_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, help_text='The image that will be displayed on the blog home page and on the post itself. (<strong>1280x720</strong>)', upload_to=blog.models.post_upload_path),
            preserve_default=False,
        ),
    ]
