# Generated by Django 2.2.1 on 2019-09-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_reply_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='update_message',
            field=models.CharField(blank=True, help_text='When you edit this reply put a reason.', max_length=200),
        ),
    ]
