# Generated by Django 2.2.1 on 2019-09-02 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_reply_update_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='update_message',
        ),
        migrations.AddField(
            model_name='reply',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='updated_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
