# Generated by Django 2.1.7 on 2019-04-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title on the homepage.', max_length=100)),
                ('tagline', models.CharField(help_text="The tagline that's under the title on the homepage.", max_length=100)),
                ('background', models.ImageField(help_text="The image that's displayed on the homepage.", upload_to='')),
            ],
            options={
                'db_table': 'home_data',
            },
        ),
    ]
