# Generated by Django 2.2.1 on 2019-05-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_class', models.CharField(choices=[('Mercenary', 'Mercenary'), ('Sniper', 'Sniper'), ('Medic', 'Medic'), ('Engineer', 'Engineer')], max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'home_character',
            },
        ),
        migrations.CreateModel(
            name='HomeCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title on the homepage.', max_length=100)),
                ('tagline', models.CharField(help_text="The tagline that's under the title on the homepage.", max_length=100)),
                ('background', models.ImageField(help_text="The image that's displayed on the homepage.", upload_to='')),
                ('video_link', models.URLField(blank=True, help_text='The url for the video that will be on the homepage.')),
            ],
            options={
                'db_table': 'home_carousel',
            },
        ),
        migrations.CreateModel(
            name='HomeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'home_data',
            },
        ),
    ]
