# Generated by Django 2.0.13 on 2019-04-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGESite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedata',
            name='video_link',
            field=models.URLField(default='', help_text='The url for the video that will be on the homepage.'),
            preserve_default=False,
        ),
    ]
