# Generated by Django 2.2.1 on 2019-05-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGESite', '0002_homedata_video_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_class', models.CharField(choices=[('Mercenary', 'Mercenary'), ('Sniper', 'Sniper'), ('Medic', 'Medic'), ('Engineer', 'Engineer')], max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'home_character',
            },
        ),
        migrations.CreateModel(
            name='HomeCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title on the homepage.', max_length=100)),
                ('tagline', models.CharField(help_text="The tagline that's under the title on the homepage.", max_length=100)),
                ('background', models.ImageField(help_text="The image that's displayed on the homepage.", upload_to='')),
                ('video_link', models.URLField(help_text='The url for the video that will be on the homepage.')),
            ],
            options={
                'db_table': 'home_carousel',
            },
        ),
        migrations.RemoveField(
            model_name='homedata',
            name='background',
        ),
        migrations.RemoveField(
            model_name='homedata',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='homedata',
            name='title',
        ),
        migrations.RemoveField(
            model_name='homedata',
            name='video_link',
        ),
        migrations.AddField(
            model_name='homedata',
            name='about',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homedata',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
