# Generated by Django 2.2.1 on 2019-05-05 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CGESite', '0003_auto_20190505_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecarousel',
            name='homedata',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CGESite.HomeData'),
            preserve_default=False,
        ),
    ]
