# Generated by Django 2.2.1 on 2019-05-05 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CGESite', '0004_homecarousel_homedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecarousel',
            name='homedata',
        ),
    ]
