# Generated by Django 2.2.1 on 2019-05-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGESite', '0005_remove_homecarousel_homedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='body',
        ),
        migrations.AlterField(
            model_name='homecarousel',
            name='video_link',
            field=models.URLField(blank=True, help_text='The url for the video that will be on the homepage.'),
        ),
    ]
